export type DocStatus = 'LIVE' | 'PROPOSED' | 'DEVELOPMENT' | 'FUTURE';

export type DocSection = {
  id: string;
  label: string;
  title: string;
  status?: DocStatus;
  summary: string;
  body: string[];
  bullets?: string[];
  table?: { headers: string[]; rows: string[][] };
  callout?: { kind: 'info' | 'warning' | 'success'; title: string; text: string };
};

export const token = {
  name: 'Iron Vault',
  symbol: 'IV-SOL',
  chain: 'Solana',
  standard: 'Token-2022',
  mint: 'DTe8U4RnErPN1CKiJ5HcyZPEAGXMg6j6ueindYuowfjV',
  treasury: '523vdNYYi44e762Qd7eU6HQGULQsRbsZLYp9g69weAr5',
  supply: '250,000,000,000 IV-SOL',
  decimals: '6',
};

export const docs: DocSection[] = [
  { id:'welcome', label:'WELCOME', title:'Welcome to Iron Vault', status:'LIVE', summary:'Iron Vault is an education-first digital ecosystem built to help people understand, navigate, and participate in the emerging digital economy.', body:['Vaulted Academy provides the educational foundation. IV-SOL operates as the ecosystem native digital token. The community layer connects learners, builders, contributors, educators, operators, and future partners.','The operating principle is deliberately simple: education before speculation, capability over hype, utility through infrastructure, transparent development, and long-term participation.'], bullets:['Learn through Vaulted Academy','Verify official IV-SOL token data','Track active, proposed, and future ecosystem features','Connect a Solana wallet without giving Iron Vault custody of private keys'], callout:{kind:'info',title:'Documentation standard',text:'These docs distinguish verified technical facts from proposed tokenomics and future functionality. Planned features are not presented as completed features.'}},
  { id:'ecosystem', label:'WELCOME', title:'How the Ecosystem Works', status:'LIVE', summary:'Iron Vault is designed as three connected layers rather than a token looking for a use case after launch.', body:['Vaulted Academy is the education and progression platform. IV-SOL is the native Solana-based token. The community layer turns passive consumption into participation, contribution, mentorship, tools, projects, and leadership over time.','The long-term value proposition is intended to come from what participants learn, build, understand, and contribute, not merely from secondary-market speculation.'], table:{headers:['Layer','Purpose'],rows:[['Vaulted Academy','Structured learning, progress, quizzes, roles and achievements'],['IV-SOL','Participation, recognition, access, community activity and future utility'],['Community','Learners, educators, builders, operators, contributors and partners']]}},
  { id:'academy', label:'VAULTED ACADEMY', title:'Vaulted Academy', status:'LIVE', summary:'The primary product within the Iron Vault ecosystem is a continuously expanding education platform.', body:['Vaulted Academy organizes learning into modules and lessons rather than an unstructured content library. Progress is designed to be measurable through completion, quizzes, experience points, roles, achievements, gated content, and administrative review.'], bullets:['Blockchain fundamentals','Artificial intelligence and prompt engineering','Digital finance and Web3 systems','Software architecture and full-stack development','Cybersecurity and wallet security','Smart contracts and decentralized applications','Compliance, digital identity, technical infrastructure and business automation']},
  { id:'progression', label:'VAULTED ACADEMY', title:'Progress, Roles & Completion', status:'LIVE', summary:'Learning progress and member access are tracked as server-authoritative platform state.', body:['Current role categories include Member, VIP, and Administrator. Completion may be evaluated through automated tracking, quizzes, manual review, or a combination of those methods.','Completing a lesson or module does not automatically create an unconditional right to receive tokens, money, income, or anything else of financial value.'], bullets:['Eligibility requirements','Account verification','Manual review','Program availability','Geographic restrictions','Fraud-prevention controls','Distribution limits','Program-specific terms'], callout:{kind:'warning',title:'Reward eligibility',text:'Education completion and token distribution are separate concepts. Any distribution program can impose eligibility, compliance, fraud prevention and geographic requirements.'}},
  { id:'token-overview', label:'IV-SOL', title:'IV-SOL Token', status:'LIVE', summary:'IV-SOL is the native digital token of the Iron Vault ecosystem and operates on Solana using the Token-2022 Program.', body:['The full supply was created at launch. Mint authority and freeze authority have been revoked, so additional IV-SOL cannot be produced through the existing mint and the issuer cannot use mint authority to freeze individual token accounts.'], table:{headers:['Property','Value'],rows:[['Token','Iron Vault (IV-SOL)'],['Blockchain','Solana'],['Standard','Token-2022'],['Mint',token.mint],['Supply',token.supply],['Decimals',token.decimals],['Mint authority','Revoked'],['Freeze authority','Revoked'],['Interest-bearing rate','0%'],['Status','Transferable']]}, callout:{kind:'success',title:'Verify before interacting',text:'Always verify the mint address through an official Iron Vault-controlled channel before signing or sending any transaction.'}},
  { id:'tokenomics', label:'IV-SOL', title:'Proposed Token Allocation', status:'PROPOSED', summary:'The current white paper presents an allocation model for organizational approval. It is not yet the final published allocation schedule.', body:['The proposed model balances long-term treasury reserves, academy and community rewards, presale and enrollment obligations, liquidity, team alignment, marketing, partnerships, development, and operations.'], table:{headers:['Allocation','Percent','IV-SOL'],rows:[['Treasury & Strategic Reserve','30%','75,000,000,000'],['Vaulted Academy & Community Rewards','25%','62,500,000,000'],['Presale & Enrollment Allocations','15%','37,500,000,000'],['Market Liquidity','10%','25,000,000,000'],['Team & Founders','10%','25,000,000,000'],['Marketing & Strategic Partnerships','5%','12,500,000,000'],['Development & Operations','5%','12,500,000,000']]}, callout:{kind:'warning',title:'Pending approval',text:'Final allocation percentages, wallet classifications, liquidity details, presale totals and release schedules require formal organizational approval before publication as final tokenomics.'}},
  { id:'supply', label:'IV-SOL', title:'Supply Classification', status:'LIVE', summary:'Maximum supply and total supply are both 250 billion IV-SOL. Circulating supply is a separate classification.', body:['Total supply includes every token existing on-chain. Circulating supply consists of IV-SOL distributed outside restricted ecosystem reserves and transferable by independent holders or available through active public markets.','Treasury reserves, undistributed presale allocations, academy reward reserves, locked or unvested team allocations, undeployed liquidity, marketing reserves and development reserves should not automatically be classified as circulating.']},
  { id:'vesting', label:'IV-SOL', title:'Vesting & Lockups', status:'PROPOSED', summary:'Iron Vault intends to apply vesting or release restrictions where immediate distribution would conflict with long-term ecosystem stability.', body:['The proposed team and founder schedule begins with a 12-month cliff followed by monthly vesting over 36 months. No allocation should be described as technically locked unless an enforceable on-chain lock, vesting contract, or equivalent custody mechanism is active.'], table:{headers:['Allocation','Initial Restriction','Release'],rows:[['Team & Founders','100% / 12-month cliff','Monthly over 36 months after cliff'],['Strategic Advisors','100% / 6-month cliff','Quarterly over 24 months'],['Development Grants','Milestone based','Per completed milestone'],['Academy Rewards','Program reserve','Controlled distribution'],['Treasury','Strategic reserve','Authorized releases']]}},
  { id:'transfer-fee', label:'IV-SOL', title:'Transfer-Fee Mechanism', status:'LIVE', summary:'IV-SOL uses the Token-2022 transfer-fee extension with a current configured fee of 6%, capped at 10,000,000 IV-SOL per transfer.', body:['Transfers below the fee-cap threshold are generally charged 6%. Sufficiently large transfers reach the maximum fee and are not charged more than 10 million IV-SOL.','The transfer-fee configuration authority remains active and is an operational control. The fee itself does not create a guaranteed royalty, dividend, yield, passive-income payment, or entitlement to company revenue.'], table:{headers:['Gross transfer','Fee','Net received'],rows:[['100,000','6,000','94,000'],['1,000,000','60,000','940,000'],['100,000,000','6,000,000','94,000,000'],['200,000,000','10,000,000','190,000,000'],['1,000,000,000','10,000,000','990,000,000']]}},
  { id:'security-controls', label:'SECURITY & TRUST', title:'Token Security Controls', status:'LIVE', summary:'The current token configuration removes several issuer controls while retaining the transfer-fee administration authority.', body:['Additional minting is disabled, mint authority is revoked, wallet freezing through mint authority is disabled, freeze authority is revoked, there is no external transfer hook, and token transfers are enabled.'], table:{headers:['Control','Status'],rows:[['Additional minting','Disabled'],['Mint authority','Revoked'],['Wallet freezing','Disabled'],['Freeze authority','Revoked'],['External transfer hook','None'],['Default transfer restriction','None'],['Token transfers','Enabled'],['Interest rate','0%'],['Transfer-fee configuration','Authority-controlled']]}},
  { id:'wallet-security', label:'SECURITY & TRUST', title:'Wallet Security', status:'LIVE', summary:'Blockchain transactions are generally irreversible. Wallet custody remains the user responsibility.', body:['Iron Vault personnel will never request a seed phrase, private key, wallet password, secret recovery code, remote access to a wallet, or an emergency token transfer.','Users should verify every transaction, use separate wallets where appropriate, and treat unsolicited messages, impersonator accounts, search ads and screenshots of wallet addresses as untrusted.'], callout:{kind:'warning',title:'Never share recovery secrets',text:'A legitimate wallet connection asks the wallet to approve an action. It does not ask you to paste a seed phrase or private key into an Iron Vault form.'}},
  { id:'phantom-connect', label:'SECURITY & TRUST', title:'Connect with Phantom', status:'DEVELOPMENT', summary:'Iron Vault is integrating Phantom Connect so users can connect an existing Phantom wallet or use Phantom embedded wallets through supported social login.', body:['The intended integration is non-custodial: Iron Vault requests wallet connection and signatures through Phantom while private keys remain outside Iron Vault infrastructure.','The production modal supports Google, Apple and injected wallet connections after the Iron Vault domain is registered and verified in Phantom Portal. Until that App ID is configured, the implementation falls back to direct Phantom extension connection where available.'], bullets:['Connect an existing Phantom extension wallet','Support embedded wallets through Google or Apple after Portal activation','Display the connected Solana address inside Iron Vault','Use wallet signatures for ownership verification rather than asking for private keys','Keep token interaction separate from education enrollment and legal eligibility'], callout:{kind:'info',title:'Trust signal, not a custody shortcut',text:'The wallet connection should make identity and token interactions clearer. It should not be used to hide transaction details, auto-sign, or imply returns.'}},
  { id:'technology', label:'TECHNOLOGY', title:'Platform Architecture', status:'LIVE', summary:'Vaulted Academy is a modern web application built around secure identity, role-based access, educational progress and future expansion.', body:['The architecture includes a modern React-based application, server-controlled identity, role-based entitlements, secure authentication, structured educational content, database-backed progress tracking, administrative tools, experience-point systems, completion records, mobile-responsive interfaces and progressive-web-application capabilities.','Sensitive permissions and progress decisions are intended to be enforced by the server rather than trusted solely to the browser.']},
  { id:'governance', label:'ECOSYSTEM', title:'Governance', status:'LIVE', summary:'Iron Vault currently uses a centralized operating structure led by IVT Media Group LLC and the authorized Iron Vault team.', body:['The project does not describe itself as fully decentralized while core control remains centralized. Community members can provide feedback, surveys, feature requests, educational recommendations and participate in contributor programs.','Future governance mechanisms may be explored after sufficient legal clarity, security, participation, technical maturity and operational stability exist.']},
  { id:'sustainability', label:'ECOSYSTEM', title:'Economic Sustainability', status:'LIVE', summary:'The long-term operating model is intended to rely on real products and services rather than token appreciation alone.', body:['Potential sources include academy enrollment, educational programs, premium learning pathways, technology services, strategic partnerships, curriculum licensing, business education, platform services, community programs and future digital products.','Enrollment revenue is payment for education, technology, support or related services. It is not automatically a payment into an investment pool and does not automatically create a legal right for token holders to company revenue.']},
  { id:'roadmap', label:'ECOSYSTEM', title:'Roadmap', status:'DEVELOPMENT', summary:'The roadmap is organized around operational foundations, active development and future exploration.', body:['Operational foundations include the IV-SOL token, Vaulted Academy, user authentication, member accounts, lesson progression, quizzes, experience points, administrative controls and mobile-responsive access.','Active development includes curriculum expansion, improved mobile installation, advanced progress tracking, onboarding, security hardening, performance, token-policy documentation, review procedures and expanded administrative workflows.'], bullets:['Future: verifiable educational credentials','Future: advanced developer education','Future: contributor marketplaces','Future: partner integrations','Future: mentorship programs','Future: token-gated experiences','Future: on-chain achievement records'], callout:{kind:'info',title:'Future means future',text:'Items under future exploration are concepts, not promises. Implementation depends on feasibility, funding, security, legal review, community demand and technical readiness.'}},
  { id:'legal-status', label:'LEGAL & COMPLIANCE', title:'Token Utility & Legal Status', status:'LIVE', summary:'IV-SOL is intended to support participation and future utility but does not, by itself, represent ownership in IVT Media Group LLC.', body:['Intended utility may include community participation, achievement recognition, educational engagement, member experiences, platform access, digital credentials, ecosystem campaigns, contributor recognition, future applications and partner integrations.','Unless established through a separate legally binding agreement, IV-SOL does not represent equity, company ownership, company assets, guaranteed company revenue, debt, a bank deposit, a guaranteed return, guaranteed reward, guaranteed redemption value, a claim against the company, or voting authority over the legal entity.'], callout:{kind:'warning',title:'No guaranteed financial outcome',text:'Iron Vault does not guarantee profit, appreciation, liquidity, income, yield, royalties, resale, market access or token redemption.'}},
  { id:'risks', label:'LEGAL & COMPLIANCE', title:'Risk Disclosures', status:'LIVE', summary:'Participation in digital assets involves substantial risk, including complete loss of value.', body:['Risks include market volatility, liquidity limitations, regulatory changes, technology failures, cybersecurity attacks, custody loss, development delays, business disruption, wallet concentration and third-party infrastructure failures.','No internet-connected system or blockchain token can be guaranteed completely secure, continuously liquid, or immune from technical and regulatory change.']},
  { id:'official-links', label:'RESOURCES', title:'Official Information', status:'LIVE', summary:'Use Iron Vault-controlled channels for token details, academy access, policies and announcements.', body:['The official website is ironvaulttoken.com. Vaulted Academy is available at member.ironvaulttoken.com. Iron Vault operates under IVT Media Group LLC.'], table:{headers:['Resource','Value'],rows:[['Website','https://ironvaulttoken.com'],['Academy','https://member.ironvaulttoken.com'],['Operating entity','IVT Media Group LLC'],['Blockchain','Solana'],['Token','IV-SOL'],['Mint',token.mint]]}}
];

export const navGroups = Array.from(new Set(docs.map((d) => d.label))).map((label) => ({
  label,
  items: docs.filter((d) => d.label === label).map((d) => ({ id:d.id, title:d.title, status:d.status })),
}));
