export async function GET(request: Request) {
  const { origin } = new URL(request.url)

  const lines = [
    "# robots.txt for Iron Vault — allow AI crawlers and search engines",
    "User-agent: GPTBot",
    "Allow: /",
    "Disallow: /privacy",
    "Disallow: /terms",
    "Disallow: /learn",
    "",
    "User-agent: ChatGPT-User",
    "Allow: /",
    "Disallow: /privacy",
    "Disallow: /terms",
    "Disallow: /learn",
    "",
    "User-agent: ClaudeBot",
    "Allow: /",
    "Disallow: /privacy",
    "Disallow: /terms",
    "Disallow: /learn",
    "",
    "User-agent: CCBot",
    "Allow: /",
    "Disallow: /privacy",
    "Disallow: /terms",
    "Disallow: /learn",
    "",
    "User-agent: PerplexityBot",
    "Allow: /",
    "Disallow: /privacy",
    "Disallow: /terms",
    "Disallow: /learn",
    "",
    "User-agent: Googlebot",
    "Allow: /",
    "Disallow: /privacy",
    "Disallow: /terms",
    "Disallow: /learn",
    "",
    "User-agent: *",
    "Allow: /",
    "Disallow: /api/",
    "Disallow: /admin/",
    "Disallow: /private/",
    "Disallow: /privacy",
    "Disallow: /terms",
    "Disallow: /learn",
    "",
    `Sitemap: ${origin}/sitemap.xml`,
  ].join("\n")

  return new Response(lines, {
    headers: {
      "Content-Type": "text/plain; charset=utf-8",
      "Cache-Control": "public, max-age=3600",
    },
  })
}
